### ISSUE TITLE
Rocket game - Score board

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#10]
Nezobrazuje se score z předchozího bloku hraní (hraní minihry 5 min v kuse, několik pokusů). Tyto informace se načtou po vypnutí a zapnutí minihry.

**Comment by TomasKermes** [comment]
Zdá se, že po vypnutí a zapnutí minihry se všechna data načtou správně

**Comment by JacobCube** [comment]
Prodiskutováno o MAP 21/10.
Prosím o otestování dle popsané očekávané funkcionality, případně přepracování tohoto issue.
Vytvořil jsem popis této funkcionality v GitHubu

**Comment by JacobCube** [comment]
Již uběhl téměř měsíc a nedošlo k otestování.

**Comment by TomasKermes** [comment]
> Prodiskutováno o MAP 21/10.
> Prosím o otestování dle popsané očekávané funkcionality, případně přepracování tohoto issue.
> Vytvořil jsem popis této funkcionality v GitHubu

Poslední update CubeIttu byl vydán 19.10. Je toto zahrnuto v onom updatu, nebo si budu muset zažádat o verzi, která nebyla vydána na Google play?

**Comment by TomasKermes** [comment]
> Prodiskutováno o MAP 21/10.
> Prosím o otestování dle popsané očekávané funkcionality, případně přepracování tohoto issue.
> Vytvořil jsem popis této funkcionality v GitHubu

Polsední verze byla publikovaná 19.10. je tato funkcionalita zahrnuta i v této verzi nebo si budu muset zažádat o verzi pracovní?

**Comment by TomasKermes** [comment]
Otestováno na novém účtu(online/online). Minihra se chová podle popisu v dokumentaci jedná-li se o nového hráče. Otestován i pětiminutový delay. Po odehrání score, které by se mělo zařadit na 4. místo v tabulce. Po X minutách se data zobrazila správně ve scoreboard. Vše je tedy vpořádku.

Omlouvám se za nedorozumění a značné zpoždění v testování.

**Comment by JacobCube** [comment]
Ok, nic se neděje, nemohl jsi to vědět.
