### ISSUE TITLE
Nekonečný loop emailu s odměnami po registraci

### ISSUE THREAD

**Issue by DoctorFryder** [max7kmrk/CubeIt_Testing#12]
Po registraci a následném vybrání odměn z emailu za registraci, se hráč dostane do nekonečného loopu, kde mu pořád přichází email s odměnami za registraci.

**Comment by DoctorFryder** [comment]
[Link k videu.](https://www.youtube.com/watch?v=0LgINhAoQBY&feature=youtu.be)

**Comment by JacobCube** [comment]
Pravidla databáze zamítly požadavek na smazání mailu.
Write failed at users/yeetmeow/Inbox/9Hb3kEKbUQsRTrXZ3N75: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
