### ISSUE TITLE
Mizení Cubeixů

### ISSUE THREAD

**Issue by DoctorFryder** [max7kmrk/CubeIt_Testing#14]
Cubeixy po odhlášení a následném opětovném přihášení mizí.

**Comment by JacobCube** [comment]
Mizí jenom cubixy? To znamená, že vše se uloží, ale jediné cubixy ne?

**Comment by JacobCube** [comment]
Tomuto zabraňuje bezpečností pravidlo. Na vyzvedávání odměn budou potřeba databázové funkce, které zatím nejsou (nezapisuje to hráčovo zařízení, ale server).
