### ISSUE TITLE
Popis itemu "přetéká" přes rámeček itemu

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#15]
![image](https://user-images.githubusercontent.com/45394822/71524869-a8968700-28cf-11ea-8d59-1796c31efcd6.png)

- Description Itemu přesahuje z rámečku
-> box ve kterém se zobrazuje text je vetší než rámeček samotný

**Comment by JacobCube** [comment]
Opraveno v nadcházející verzi
