### ISSUE TITLE
Interface postavy

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#17]
Při vstupu z hlavní obrazovky do postavy není možně zobrazit statistiku nasazeného itemu dokud ho

1. nesundáme
2. neklikneme na item v batohu, který postava právě nenosí

**Comment by JacobCube** [comment]
O jakou verzi hry se jedná? Issues potřebují více informací.

**Comment by TomasKermes** [comment]
Jedná se o verzi v0.5.0.5
