### ISSUE TITLE
Rocket Game

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#3]
Raketka má moc velký hitbox. Je to jeden velký obdélník což zapříčiňuje špatný odhad + meteor hráče trefí i když se nedotkl přímo raketky.

**Comment by JacobCube** [comment]
Jedná se o apha verzi - konkrétně v RocketGame nemáme custom grafiku, aktuální grafika jestažená z internetu, Co se týče hitboxů, tak ty vytvořím až s novou grafikou, teď to nemá smysl.
