### ISSUE TITLE
Ghost menu

### ISSUE THREAD

**Issue by DoctorFryder** [max7kmrk/CubeIt_Testing#4]
**Verze: Jakákoliv**
**Popis:** "Ghost menu" je stav hry kdy je uživatel v menu i přesto, že není přihlášen, má přístup ke všem funkcím jako kdyby byl přihlášený. Nastane po crashnutí hry.
Chování:
**Mail** - Prázdný email, je možné posílat a číst zprávy, po další crashutí hry se daný stav "Mailu" uloží. Poslanou zprávu její příjemce nevidí.
**Shop** - Uživatel si nemůže nic koupit. Při pokusu o to crashne hra a resetuje se inventář.
**Market** - Je možné kupovat věci z "Marketu". dané věci následně odeberou z "Marketu" i pro ostatní hráče.
**Character/Inventář** - Hra crashne.
**Frakce** - Prázdná obrazovka vytváření frakce, možnost pouze přidat či odebrat uživatele "MexxFM". Frakci je možné si založit, možnost pouze přidat či odebrat uživatele "MexxFM" Frakce je viditelná pro ostatní hráče.
**Kabina** - Je možné začít hrát příběh.
**Síň slávy/Aréna** - Je možné vidět tabulku s ostatními uživateli, Při kliknutí na jméno uživatele hra crashne.
**Mapa** - Je možné se pohybovat po mapě. Nejsou zde žádné questy.
**Výběr spellů** - Všechny spelly jsou "Block", dají se vybírat.
**Testovací zóna** - Při testu proti AI je uživatel přesunut do nekonečné "Loading screen". Při pokusu o odchod z "Loading screen" hra crashne.
**Nastavení** - Všechny možnosti fungují.

**Comment by DoctorFryder** [comment]
Omlouvám se za ty gramatické chyby, prostě jsem je přehlédl.

**Comment by DoctorFryder** [comment]
[Ukázka](https://www.youtube.com/watch?v=zsbUPm9wieI) kupování itemů v Marketu. Prosím, nevšímejte si zvuku v pozadí.

**Comment by JacobCube** [comment]
Cíl bug reportu je přijít na důvod nastání bugu, prosil bych tedy věci týkající se bugu, nikoliv chování aplikace po nastání bugu (aneb "side effect"). 
O "Ghost menu" se již ví, nicméně se nejdná o nic, co by se dalo využít - do default účtu se nedá přihlásit, je to neexistující účet a nikam se neukládá.
Note: Nekonečný loading screen nastane pokaždé, když se přihlášená osoba snaží načíst z databáze, avšak protože to je neexistující účet, tak se načítá do nekonečna.

**Comment by JacobCube** [comment]
Taky prosím o snahu v rámci pochopitelnosti řešitele, potřebuji vědět co je problém, jak ho vyřešit, a jak ho duplikovat, abych dokázal najít přesnou příčinu. Děkuju

**Comment by JacobCube** [comment]
Question: Víš co ten "Ghost menu" způsobilo? Případně uzavřít. Díky

**Comment by JacobCube** [comment]
Nedostatek informací
