### ISSUE TITLE
Crashnutí hry při vypínání ("Exit")

### ISSUE THREAD

**Issue by DoctorFryder** [max7kmrk/CubeIt_Testing#5]
**Verze: 0.4.9.6**
**Popis:** Při kliknutí na tlačítko "Exit" hra crashne*.
_*Crash vede k bílému záblesku obrazovky po kterém následuje přesun na/do:_

**a)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry rovnou stiskne tlačítko "Exit".
**b)** Prázdný "Mail" pokud hráč po přihlášení se do hry šel nejdříve do mailu. Následně je uživatel "uzavřem" v "[Ghost menu](https://github.com/max7kmrk/CubeIt_Testing/issues/4)"
**c)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Shopu".
**d)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Marketu".
**e)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Character".
**f)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Kabiny/Příbehu".
**g)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Arény".
**h)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Mapy".
**i)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Testovny/Vybírání spellů".
**j)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Frakce".
**k)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Nastavení".
**l)** Nekonečná "Loading screen" pokud hráč po přihlášení se do hry šel do "Rocket Game".
**m)** (V "[Ghost menu](https://github.com/max7kmrk/CubeIt_Testing/issues/4)") Nekonečná "Loading screen", při pokusu o odchod (tlačítko "Back" na telefonech) je uživatel navrácen do "Mailu" v "[Ghost menu](https://github.com/max7kmrk/CubeIt_Testing/issues/4)".

V příloze jsou výsledky testování dané chyby.
[Issue N.5 - Testing.xlsx](https://github.com/max7kmrk/CubeIt_Testing/files/3639151/Issue.N.5.-.Testing.xlsx)

**Comment by JacobCube** [comment]
Kopíruji z #4 : Cíl bug reportu je přijít na důvod nastání bugu, prosil bych tedy věci týkající se bugu, nikoliv chování aplikace po nastání bugu (aneb "side effect").
O "Ghost menu" se již ví, nicméně se nejdná o nic, co by se dalo využít - do default účtu se nedá přihlásit, je to neexistující účet a nikam se neukládá.
Note: Nekonečný loading screen nastane pokaždé, když se přihlášená osoba snaží načíst z databáze, avšak protože to je neexistující účet, tak se načítá do nekonečna.
Taky prosím o snahu v rámci pochopitelnosti řešitele, potřebuji vědět co je problém, jak ho vyřešit, a jak ho duplikovat, abych dokázal najít přesnou příčinu. Děkuju

**Comment by JacobCube** [comment]
Question: Exit button má 2 stavy - swipe, click a otevření menu. Prosím o deailnější popis opravdového bugu pro rychlejší řešení z mojí strany. Tedy postupovat takto: zkusit zreplikovat daný problém, nedá-li se, tak musí být chyba ve vztahu s něčím jiným a testovat po dvojicích akcí apod.
Díky

**Comment by JacobCube** [comment]
Omezil jsem stav hry "Ghost menu". Uživateli by to mělo oznámit, že nastala chyba a odhlásí se.

**Comment by JacobCube** [comment]
Nedostatek informací.
Narazil jsem na obdobný problém z důvodu změny background hudby. Opraveno.
Pokud se to vrátí, prosím o návod k replikování.
