### ISSUE TITLE
RocketGame 

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#6]
**Verze: 0.4.9.6**
**Issues:** 
- Raketka má moc velký hitbox. Zaznamenává kolizi tam, kde není obrázek raketky -> kazí hru.
- Problikává čas/score. Platí pro všechny 3 fonty.
- Pokud hráč sebere zmenšující PowerUp (red mushroom) a následně zvětšující PowerUp (brown mushroom), pak hra chashne a následně nastane "[Ghost menu](https://github.com/max7kmrk/CubeIt_Testing/issues/4)". Stejná situace platí pro speed (cukr) a slow (soulsand). Jelikož proti sobě působí jako debufy, tak to crashne hru.

![Screenshot_20190922_151637_cz cubeit cubeit](https://user-images.githubusercontent.com/45394822/65388637-0b670800-dd4e-11e9-9ba8-965d999dd82d.jpg)

![Screenshot_20190922_145937_cz cubeit cubeit](https://user-images.githubusercontent.com/45394822/65388517-bd9dd000-dd4c-11e9-9157-074346d0441f.jpg)

**Comment by TomasKermes** [comment]
ten problém s PowerUpy  by se asi dal vyřešit negenerováním toho druhého. Chci probrat zítra. Klidně jen o přestávce.

**Comment by DoctorFryder** [comment]
Potvrzuji, po sebrání dvou itemů/PowerUpů s opačným efektem je uživatel přesunut do [Ghost menu](https://github.com/max7kmrk/CubeIt_Testing/issues/4).

**Comment by JacobCube** [comment]
Power upy jsem již opravil, zneaktivní se první a následně aktivuje nový. Ve verzi 0.9.4.6 byl potřeba jen delay mezi těmito operacemi. Díky

**Comment by JacobCube** [comment]
Také prosím o report bugů zvlášť, s tímhle se špatně pracuje. Díky

**Comment by JacobCube** [comment]
1. Duplicitní report. Ten prvotní je již uzavřen.
2. Spíše glitch, nicméně se na to podívám, díky.
3. Opraveno ve verzi 0.4.9.7 - uploadnu během několika hodin pro další testování.

**Comment by JacobCube** [comment]
2. Opraveno ve verzi 0.4.9.7. Kdyby se glitch objevil znovu, tak prosím o vytvoření reportu zvlášť.
