### ISSUE TITLE
Item price

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#7]
**Itemy**
- Cena všech itemů je **0**
- nejdou koupit
- když je hráč prodá nedostane nic
- platí i pro itemy z questů

**Comment by DoctorFryder** [comment]
O problému se ví, jedná se o problém stahující se na starou verzi aplikace. Itemy ze starší verze (v inventáři a obchodě) stojí 0. Nově vygenerované itemy mají cenu.

**Comment by TomasKermes** [comment]
Ok. Uzavírám Issue
