### ISSUE TITLE
Questy 

### ISSUE THREAD

**Issue by TomasKermes** [max7kmrk/CubeIt_Testing#8]
- Po rozkliknutí questu jsou reward coiny 0. (Platí pro coiny u jejich ikonky. Zobrazení coinů v textu je vpořádku).
- Quest se dá přijmout + progess je ok
- Po kliknutí na hotový quest (fight + vyzvednutí rewardu) hra crashne a zobrazí se shop plný štítů(stojí 0).
- Jakmile hráč odejde z obchodu hra vyhodí chybu **"thats not where ur souposed to be"**  a hráč se dostane do infinite loading screanu -> do mailu a takto dokola.

 Dost pravděpodobně to má spojitost s #7.

**Comment by TomasKermes** [comment]
Považuji Questy za kompletně nefunkčí v této verzi

**Comment by DoctorFryder** [comment]
O problému se ví, jedná se o problém stahující se na starou verzi aplikace. Questy jsou vygenerované starší verzí aplikace, nově vygenerovaná questy fungují.

**Comment by TomasKermes** [comment]
Ok rozuměno. Uzavírám Issue

**Comment by DoctorFryder** [comment]
Při crashnutí aplikace v Mapě a znovu-zapnutí aplikace, z questu není žádná odměna a daný item stojí 0.

**Comment by JacobCube** [comment]
Plnění misí funguje tak, že při splnění mise určitého "surface" se celá surface refreshne (přegenerují se questy). Tato akce se však neukládá okamžitě. Proto, pokud ti to spadne, vrátí se ti questy, které jsi měl při posledním uložení, problém bude spíše s tím, že ti to spadlo. Případně vyzkoušej tu samou věc při nových questech a i uložených, stávat by se to nemělo.
