### ISSUE TITLE
Inbox listener

### ISSUE THREAD

**Issue by DoctorFryder** [max7kmrk/CubeIt_Testing#9]
Při testování jsme došli k závěru, že tato funkce jak funguje tak i nefunguje, záleží na verzi androidu.
Testování proběhlo na Android verzích 7.0 a 9.0.
Na verzi 9.0 proběhalo vše bez problémů.
Na verzi 7.0 nedocházelo k automatickému obnovování Emailu. Muselo se vždy jít nejdříve do menu a potom zpět.

**Comment by JacobCube** [comment]
Rozumím problému, příště prosím o podrobnější test / popis. Tedy co konkrétně funguje, co konkrétně nefunguje - listener funguje v případě, že nemám otevřenou poštu. Nefunguje v případě, kdy poštu mám otevřenou, přišlo mi upozornění, ale zpráva není viditelná v poště.
